export default {
	USER_AUTH_TOKEN: '@USER_AUTH_TOKEN',
	USER_LANGUAGE: '@USER_LANGUAGE',
	DONE_ONBOARD: '@DONE_ONBOARD',
	AGREED_PRIVACY_POLICY: '@AGREED_PRIVACY_POLICY',
	USER_ID: '@USER_ID',
	USER_APPLOCK_PIN: '@USER_APPLOCK_PIN',
	USER_APPLOCK_ENABLE_BIOMETRIC: '@USER_APPLOCK_ENABLE_BIOMETRIC',
	USER_SUBSCRIPTIONS: '@USER_SUBSCRIPTIONS',
	// USER_MODE: '@HKUST.CATERER.USER_MODE',
	PUSH_TOKEN: '@PUSH_TOKEN',
	ECARD_DETAILS: '@ECARD_DETAILS',
	// for managing local notification
	LOCAL_NOTIFICATION_IDS: '@LOCAL_NOTIFICATION_IDS',
	PUSH_NOTIFICATION_ID: '@PUSH_NOTIFICATION_ID'
};
